### ISSUE TITLE
Username cannot contain a dot (.)

### ISSUE THREAD

**Issue by klacol** [abrudtkuhl/WordPressSharp#63]
Nice project here, thank you!

I have found, that a username can not contain a dot (.)

Could be an issue of the c# wrapper or of the API.

**Comment by abrudtkuhl** [comment]
Dots in usernames are not allowed in WordPress so the problem lies there. You can override that if you need.

**Comment by klacol** [comment]
ah, ok. In fact I can put in a dot into the username in the WP UI. This would be a bug there then. Thanks.

**Comment by abrudtkuhl** [comment]
I dont know that it's a bug in as much as it's a feature. There are a few
trac comments about it and I think it's there by design for security but
can be overridden via hook in a plugin if needed.

Andy Brudtkuhl
youmetandy.com

On Mon, Dec 19, 2016 at 1:31 PM, Klaus Aengenvoort <notifications@github.com
